# Use this workflow to deploy ARC
name: Deploy ARC
on:
  push:
    branches: main
    paths:
    - .github/workflows/controller.yaml
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Authenticate to AZ
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Set up AKS Connection
      run: az aks get-credentials --resource-group arc --name arc-poc

    - name: Run Helm Upgrade
      run: |
        helm upgrade arc \
          --install \
          --namespace "arc-system" \
          --create-namespace \
          oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set-controller