name: Deploy ARC Custom Runner Image
on:
  push:
    branches: main
    paths:
    - Dockerfile
  workflow_dispatch:
jobs:
  build-and-deploy:
    name: Build & Deploy Container Image To ACR
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Authenticate to AZ
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: 'Login To ACR'
      run: az acr login --name ${{ secrets.REGISTRY_LOGIN_SERVER }}
      
    - name: Build the frontend image and push it to ACR
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/<image-name>:${{ github.sha }}
        file: ./Dockerfile
      