name: Delete ARC Scale Sets & Controller
on:
  workflow_dispatch:
jobs:
  tear-down:
    name: Run Tear Down Process
    runs-on: ubuntu-latest
    steps:

    - name: Authenticate to AZ
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

    - name: Set up AKS Connection
      run: az aks get-credentials --resource-group arc --name arc-poc

    - name: "Uninstall All Scale Set Helm Charts" 
      run: |
        SCALE_SET_CHARTS=$(helm list -A | tail -n +2 | grep 'gha-runner-scale-set-' | grep -v 'gha-runner-scale-set-controller')
        if [ -z "${SCALE_SET_CHARTS}" ]; then
          echo "No scale set charts to cleanup."
          exit 0;
        fi
        IFS=$'\n'
        for CHART in ${SCALE_SET_CHARTS}; do 
          sleep 5;
          CHART_NAME=$(echo "${CHART}" | awk '{print $1}');
          CHART_NAMESPACE=$(echo "${CHART}" | awk '{print $2}');
          echo "Attempting to uninstall chart '${CHART_NAME}' in namespace '${CHART_NAMESPACE}'...";
          helm uninstall ${CHART_NAME} -n ${CHART_NAMESPACE};
        done
        sleep 60;

    - name: "Uninstall ARC Chart"
      run: |
        ARC_CHART=$(helm list -A | tail -n +2 | grep 'gha-runner-scale-set-controller')
        if [ -z "${ARC_CHART}" ]; then
          echo "ARC not installed."
          exit 0;
        fi
        IFS=$'\n'
        for CHART in ${ARC_CHART}; do 
          CHART_NAME=$(echo "${CHART}" | awk '{print $1}');
          CHART_NAMESPACE=$(echo "${CHART}" | awk '{print $2}');
          echo "Attempting to uninstall chart '${CHART_NAME}' in namespace '${CHART_NAMESPACE}'...";
          helm uninstall ${CHART_NAME} -n ${CHART_NAMESPACE};
        done